apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chroma-data
  labels:
    app: chroma
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard-rwo
  resources:
    requests:
      storage: 10Gi
